name: test-integration

on:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ 8.4, 8.5 ]

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring
          coverage: xdebug
      - name: Install Composer dependencies
        run: composer install -q
      - name: Test
        run: vendor/bin/phpunit --testsuite=Integration
